'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PERSON
    Public Property ID_PERSON As Integer
    Public Property FIRST_NAME As String
    Public Property LAST_NAME As String
    Public Property EMAIL As String
    Public Property MOBILE As String
    Public Property ADDRESS As String

    Public Overridable Property USER As ICollection(Of USER) = New HashSet(Of USER)

End Class
